---
title: "WOOF - Plot"
author: "Christoph Voelter"
date: "25/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggthemes)
```

```{r}
all.data <- read.table(file = "./data/WOOF_data 2016.txt", header = T, sep = "\t")

str(all.data)

agg.data<-all.data%>%
  group_by(Subject, Phase, Condition, con2, food_level)%>%
  summarise(latency=mean(Latency), success=mean(Success), se.latency=sd(Latency)/sqrt(length(Latency)), count.length=length(Latency),  se.success=sd(Success)/sqrt(length(Success)), count.success=length(Success))

turn.data<-all.data%>%
  filter(Number_of_turns>0)

agg.data.turn<-all.data%>%
  filter(Number_of_turns>0)%>%
  group_by(Subject, Phase, Condition, con2, food_level)%>%
  summarise(turns=mean(Number_of_turns), min.turns=min(Number_of_turns), max.turns=max(Number_of_turns), se.turns=sd(Number_of_turns)/sqrt(length(Number_of_turns)), count=length(Number_of_turns))

agg.data.turns2<-agg.data.turn%>%
  group_by(Phase, Condition, con2, food_level)%>%
  summarise(turns=mean(turns))

agg.data2<-agg.data%>%
  group_by(con2, food_level)%>%
  summarise(success=mean(success))
```
```{r}
success.plot<- ggplot(data=agg.data, aes(x=as.factor(Phase), y=success))+
  geom_line(aes(x=Phase, y=success))+
  geom_point()+
  geom_errorbar(aes(ymin=(success-se.success), ymax=(success+se.success)), width=0.1)+
  labs(
    y = "Success",
    x = "")+
  geom_vline(xintercept = 3.5, lty=3)+
  facet_wrap(~Subject)+
  theme_few()+
  scale_x_discrete(breaks=c("1","2","3","4","5","6", "7"), labels=c("low", "high", "high", "high", "extra", "extra", "extra"))+
  coord_cartesian(ylim = c(0, 1),  clip = "off")+
annotate(geom = "text", x = 2, y = -0.4, label = "Training", size = 3)+
  annotate(geom = "text", x = 4, y = -0.4, label = "visible", size = 3)+
  annotate(geom = "text", x = 5, y = -0.4, label = "visible", size = 3)+
  annotate(geom = "text", x = 6, y = -0.4, label = "occl.", size = 3)+
  annotate(geom = "text", x = 7, y = -0.4, label = "visible", size = 3)+
  theme(panel.spacing = unit(0.3, "lines"))


success.plot

```
```{r}
latency.plot<- ggplot(data=agg.data, aes(x=as.factor(Phase), y=latency))+
  geom_line(aes(x=Phase, y=latency))+
  geom_point()+
  geom_errorbar(aes(ymin=(latency-se.latency), ymax=(latency+se.latency)), width=0.1)+
  labs(
    y = "Latency (in sec)",
    x = "")+
  geom_vline(xintercept = 3.5, lty=3)+
  facet_wrap(~Subject)+
  theme_few()+
  scale_x_discrete(breaks=c("1","2","3","4","5","6", "7"), labels=c("low", "high", "high", "high", "extra", "extra", "extra"))+
  coord_cartesian(ylim = c(0, 120),  clip = "off")+
annotate(geom = "text", x = 2, y = -44, label = "Training", size = 3)+
  annotate(geom = "text", x = 4, y = -44, label = "visible", size = 3)+
  annotate(geom = "text", x = 5, y = -44, label = "visible", size = 3)+
  annotate(geom = "text", x = 6, y = -44, label = "occl.", size = 3)+
  annotate(geom = "text", x = 7, y = -44, label = "visible", size = 3)


latency.plot

ggsave(latency.plot, filename = "graphics/Exp2_WOOF_plot_individual_latencies.png", height = 4, width = 7, scale=0.8)

```
```{r}
turns.plot<- ggplot(data=agg.data.turn, aes(x=as.factor(Phase), y=turns))+
  geom_line(aes(x=Phase, y=turns))+
  geom_point()+
  geom_point(data=turn.data, aes( x=Phase, y=Number_of_turns ), pch=1, alpha=0.3)+
  geom_errorbar(aes(ymin=(turns-se.turns), ymax=(turns+se.turns)), width=0.1)+
  labs(
    y = "Number of turns",
    x = "")+
  geom_vline(xintercept = 3.5, lty=3)+
  facet_wrap(~Subject)+
  theme_few()+
  scale_x_discrete(breaks=c("1","2","3","4","5","6", "7"), labels=c("low", "high", "high", "high", "extra", "extra", "extra"))+
  coord_cartesian(ylim = c(0, 26),  clip = "off")+
annotate(geom = "text", x = 2, y = -10, label = "Training", size = 3)+
  annotate(geom = "text", x = 4, y = -10, label = "visible", size = 3)+
  annotate(geom = "text", x = 5, y = -10, label = "visible", size = 3)+
  annotate(geom = "text", x = 6, y = -10, label = "occl.", size = 3)+
  annotate(geom = "text", x = 7, y = -10, label = "visible", size = 3)+
  theme(panel.spacing = unit(0.3, "lines"))


turns.plot

```

```{r}
library(cowplot)

pg<-plot_grid(success.plot, turns.plot, ncol=1, labels = c("A", "B"))
pg

ggsave(pg, filename = "graphics/Exp2_WOOF_plot_individual.png", height = 7, width = 7, scale=0.8)
```

